config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get 'team', to: 'static#team'
  get 'contact', to: 'static#contact'
  get 'welcome/:user_name', to: 'static#welcome'
  get 'gossip/:gossip_id', to: 'static#gossip', as: 'gossip_pre'
  get 'user/:user_id', to: 'static#user', as: 'user_pre'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  has_many :likes, as: :imageable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :intertags
  has_many :comments
  has_many :likes, as: :imageable
  has_many :tags, through: :intertags
end

app/models/intertag.rb
# Correspond à Join Tag et Gossip
class Intertag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :intertags
  has_many :gossips, through: :intertags
  has_many :users, through: :gossips
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :tags, through: :gossips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home

    @all_gossips = Gossip.all
    @all_users = User.all
  end

  def team
  end

  def welcome
    @user = params[:user_name]
  end

  def contact
  end

  def gossip
    @current_gossip = Gossip.find(params[:gossip_id].to_i)
  end

  def user
    @current_user = User.find(params[:user_id].to_i)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PushGossipproject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>



  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
 <%= link_to "Navbar", root_path, :class => "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home", root_path, :class => "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", contact_path, :class => "nav-link"%>
      </li>
      <li class="nav-item">
         <%= link_to "Team", team_path, :class => "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>